# Generated by Django 4.2.7 on 2025-09-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
